"""One-off: extract every Lucide icon name from the vendored UMD bundle.

Parses the ``Object.freeze({__proto__:null,...})`` icon registry inside
frontend/vendor/lucide.min.js, converts each PascalCase JS identifier to the
kebab-case name ``data-lucide`` accepts, and writes them (one per line) to
homestew/services/lucide_icon_names.txt.

The conversion is verified by round-tripping through a port of Lucide's own
name parser (the kebab->PascalCase function createIcons uses): every emitted
name MUST resolve back to a real registry key, otherwise the frontend would
render a blank glyph for it. Names that fail are reported and dropped.
"""
import re
from pathlib import Path


def lucide_pascal(name: str) -> str:
    """Port of Lucide's data-lucide name parser (kebab/underscore -> PascalCase).

    Mirrors the minified ``xV``/``_V`` pair in lucide.min.js: separators are
    '-','_' and whitespace; the first kept char is lowercased then the whole
    string is capitalised, every char right after a separator is uppercased.
    """
    out = ""
    up = False
    for ch in name:
        if ch in "-_ " or ch <= " ":
            up = len(out) > 0
            continue
        if len(out) == 0:
            out += ch.lower()
        else:
            out += ch.upper() if up else ch
        up = False
    return out[:1].upper() + out[1:]


def to_kebab(ident: str) -> str:
    """PascalCase icon identifier -> canonical kebab-case data-lucide name."""
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", ident)
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", s)
    return s.lower()


root = Path(__file__).resolve().parent
src = (root / "frontend" / "vendor" / "lucide.min.js").read_text(encoding="utf-8")

m = re.search(r"Object\.freeze\(\{__proto__:null,(.*?)\}\)", src)
if not m:
    raise SystemExit("icon registry not found in lucide.min.js")

idents = re.findall(r"(?:^|,)([A-Za-z][A-Za-z0-9]*):", m.group(1))
registry = set(idents)

names: dict[str, str] = {}
bad: list[str] = []
for ident in idents:
    kebab = to_kebab(ident)
    if lucide_pascal(kebab) != ident or ident not in registry:
        bad.append(f"{ident} -> {kebab}")
        continue
    names.setdefault(kebab, ident)

# Names must also survive the API's stored-key pattern.
valid = sorted(n for n in names if re.fullmatch(r"[a-z0-9][a-z0-9_-]{0,49}", n))

out = root / "homestew" / "services" / "lucide_icon_names.txt"
out.write_text("\n".join(valid) + "\n", encoding="utf-8")

# Same list for the browser: loaded by index.html before app.js so the icon
# picker can search every glyph without an API round trip.
js = (
    "// Generated by _gen_icon_names.py from frontend/vendor/lucide.min.js —\n"
    "// do not edit by hand. Every name renders via <i data-lucide=\"...\">.\n"
    "const LUCIDE_ICON_NAMES = [\n"
    + "".join(f'    "{n}",\n' for n in valid)
    + "];\n"
)
(root / "frontend" / "lucide-icon-names.js").write_text(js, encoding="utf-8")

print(f"{len(idents)} identifiers, {len(names)} unique kebab names, "
      f"{len(valid)} written, {len(bad)} failed round-trip")
if bad:
    print("FAILED:", bad[:30])
for probe in ("refrigerator", "coffee", "washing-machine", "plug", "heater",
              "a-arrow-down", "bar-chart-3"):
    ok = probe in names and lucide_pascal(probe) in registry
    print(probe, "->", ok)
